### ISSUE TITLE
"Schedule off" isn't always received.  Suspect app failing to turn off Wifi.

### ISSUE THREAD

**Issue by HHest** [asksven/BetterWifiOnOff#97] opened 2013-01-30 14:54 UTC
When I set a delay (10s, 30s, etc), often I don't see the "Alarm received", "Wifi turned off" log entries after the "Scheduling Wifi off" entry.  

It's inconclusive to me whether the wifi is left on in those instances.  I've seen instances when wifi is indeed left on.  I've also seen instances where wifi went away, despite no "Wifi turned off" entry in log.

If I set delay to zero, I would invariably see the whole wifi off sequence.  And there is no question that the wifi does turn off.

Thanks

**Comment by asksven** [comment] 2013-01-31 17:46
Are you referring to the event Log on screen or to the logcat? Could you please add the log info so I can have a closer look into that?

**Comment by HHest** [comment] 2013-02-01 17:38
Yes I was looking at the event Log.  I've sent the debug log to you via email.  Thanks.

**Comment by HHest** [comment] 2013-02-06 16:58
My problem might stem from the "Extended Standby Mode" that I was using on my Sony Xperia U.  This mode promises to save battery, but I think it also make many applications "inactive".  The app works better after I turned this setting off.  If it is still failing to work in some instances, I haven't noticed it.

Am not sure if you can do something about this?  I'm attaching a screenshot description of this mode for your reference.  Thank you.

![Screenshot_2013-02-05-21-17-58](https://f.cloud.github.com/assets/3169669/132243/4f28da80-707e-11e2-948f-f2ee61b04daf.png)

**Comment by asksven** [comment] 2013-02-06 21:24
I will have to do some reading but his mode looks like a proprietary implementation. If wifi is turned off there is nothing bwof can do about that, if services are stopped as well (even if foreground) this would be a break in the compatibility with the android model for services. As I don't own that device I will have to think about adding logging info to catch least detect this kind of logic and have a baseline to try to implement a workaround. I would certainly recommend to not use this kind of non standard logic as it seems a little to "dump" to me

**Comment by asksven** [comment] 2013-02-11 21:22
Closed as this behavior can not be reproduced: a foreground service should never be shut down

**Closed as completed by asksven** 2013-02-11 21:22 UTC
